### ISSUE TITLE
Its me again :)

### ISSUE THREAD

**Issue by Tertaco** [MEDMEX1/Bl4ckHax-1.6.4#3]
Add GUI pls, it's too hard to add modules, set them, and change them, GUI is one of the most important parts of the hack client.
Also, there is another issue. When I relog in, all my modules are disabled and I have to turn them on again.

**Comment by MEDMEX1** [comment]
For the foreseeable future I won’t be adding clickgui because cringe, also there is no configing yet so for the time being your modules states will be reset when restarting your game
