### ISSUE TITLE
Very unprofessional behaviour.

### ISSUE THREAD

**Issue by koutsie** [MEDMEX1/Bl4ckHax-1.6.4#5]
Koutsie, I’m going to have to ask you professionally to please leave my github repository, I hope hearing from you soon, thanks bye bye.
-medmex

_Originally posted by @MEDMEX1 in https://github.com/MEDMEX1/Bl4ckHax-1.6.4/issues/4#issuecomment-802054058_

My issue wasn't resolved/issued in any meaningful manner.
I demand better reasoning.

**Comment by dorimeameno** [comment]
> Koutsie, I’m going to have to ask you professionally to please leave my github repository, I hope hearing from you soon, thanks bye bye.
> -medmex
> 
> _Originally posted by @MEDMEX1 in [#4 (comment)](https://github.com/MEDMEX1/Bl4ckHax-1.6.4/issues/4#issuecomment-802054058)_
> 
> My issue wasn't resolved/issued in any meaningful manner.
> I demand better reasoning.

hvh me bro

**Comment by koutsie** [comment]
That's a broad concept, a HVH in what? 
Minecraft?
CS:GO?
Sexual activities?

**Comment by MEDMEX1** [comment]
Guys please this is not tinder, leave

**Comment by dorimeameno** [comment]
> That's a broad concept, a HVH in what?
> Minecraft?
> CS:GO?
> Sexual activities?

cheatin.net

**Comment by dorimeameno** [comment]
> Guys please this is not tinder, leave

please reopen this issue, im tryina teach this punk an lesson

**Comment by koutsie** [comment]
> Guys please this is not tinder, leave

Closing the issue solves nothing.

**Comment by koutsie** [comment]
> > Guys please this is not tinder, leave
> 
> please reopen this issue, im tryina teach this punk an lesson

Stop acting like this is mcchat.

**Comment by dorimeameno** [comment]
> > > Guys please this is not tinder, leave
> > 
> > 
> > please reopen this issue, im tryina teach this punk an lesson
> 
> Stop acting like this is mcchat.

wahh wahh stop crying bitch, im waiting for u on cheatin

**Comment by koutsie** [comment]
> > > > Guys please this is not tinder, leave
> > > 
> > > 
> > > please reopen this issue, im tryina teach this punk an lesson
> > 
> > 
> > Stop acting like this is mcchat.
> 
> wahh wahh stop crying bitch, im waiting for u on cheatin

doriquad :thinking:

**Comment by quadruple-damage** [comment]
> > > > > Guys please this is not tinder, leave
> > > > 
> > > > 
> > > > please reopen this issue, im tryina teach this punk an lesson
> > > 
> > > 
> > > Stop acting like this is mcchat.
> > 
> > 
> > wahh wahh stop crying bitch, im waiting for u on cheatin
> 
> doriquad 🤔

What do I have to do with any of this????????

**Comment by koutsie** [comment]
github issue becoming tumblr

**Comment by dorimeameno** [comment]
> github issue becoming tumblr

shut yo BITCH ASS up nigga, you still aint on cheatin, im still waitin

**Comment by koutsie** [comment]
mmm
